[package]
name = "calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.24.0"
egui = "0.24.0"

[lib]
name = "calculator"
path = "src/lib.rs"

[[bin]]
name = "calculator"
path = "src/main.rs"